# ---------------------------------------------------------------------------
# Outputs consumed by the deployment job, the CLI and CI.
# ---------------------------------------------------------------------------

output "catalog_name" {
  description = "Unity Catalog owning the medallion schemas"
  value       = databricks_catalog.insilico_trial.name
}

output "schema_names" {
  description = "Physical schema names per medallion layer (matches StorageConfig)"
  value = {
    bronze = databricks_schema.bronze.name
    silver = databricks_schema.silver.name
    gold   = databricks_schema.gold.name
  }
}

output "table_names" {
  description = "Fully qualified tables the platform writes"
  value = {
    bronze_synthetic_cohort = "${databricks_catalog.insilico_trial.name}.${databricks_schema.bronze.name}.synthetic_cohort"
    bronze_protocols        = "${databricks_catalog.insilico_trial.name}.${databricks_schema.bronze.name}.protocol_definitions"
    silver_patient_states   = "${databricks_catalog.insilico_trial.name}.${databricks_schema.silver.name}.patient_states"
    silver_adverse_events   = "${databricks_catalog.insilico_trial.name}.${databricks_schema.silver.name}.adverse_events"
    gold_arm_summaries      = "${databricks_catalog.insilico_trial.name}.${databricks_schema.gold.name}.arm_summaries"
    gold_comparisons        = "${databricks_catalog.insilico_trial.name}.${databricks_schema.gold.name}.endpoint_comparisons"
    gold_run_manifest       = "${databricks_catalog.insilico_trial.name}.${databricks_schema.gold.name}.run_manifest"
  }
}

output "storage_credential_name" {
  description = "Unity Catalog storage credential name"
  value       = databricks_storage_credential.lakehouse.name
}

output "storage_credential_external_id" {
  description = <<-EOT
    External id generated by Databricks. Pass this back as
    -var databricks_external_id=... so the IAM trust policy can be tightened.
  EOT
  value       = try(databricks_storage_credential.lakehouse.aws_iam_role[0].external_id, "")
}

output "external_locations" {
  description = "External locations backing the lakehouse and the genomic reference data"
  value = {
    lakehouse = databricks_external_location.lakehouse.url
    genomics  = databricks_external_location.genomics.url
  }
}

output "agent_service_principals" {
  description = "Application ids of the agent service principals (used as principal names in grants and CI)"
  value       = { for key, sp in databricks_service_principal.agents : key => sp.application_id }
}

output "sql_warehouse_id" {
  description = "SQL warehouse id for BI/report consumption"
  value       = databricks_sql_endpoint.analytics.id
}

output "mlflow_experiment_path" {
  description = "MLflow experiment path used by the tracking configuration"
  value       = databricks_mlflow_experiment.simulation.name
}

output "genomics_volume_path" {
  description = "Unity Catalog volume path for raw genomic reference data (bronze.genomics_reference)"
  value       = databricks_volume.genomics_reference.id
}

output "simulation_cluster_policy_id" {
  description = "Cluster policy that caps the size and cost of simulation clusters"
  value       = databricks_cluster_policy.simulation.id
}
