"""Render reviewable snapshots of the UI into ``docs/``.

The dashboard and the Studio are HTML artefacts, but until now the only way to see
the Studio shell was to start it. This script writes both surfaces into ``docs/``
so a reviewer can open them directly, attach them to a pull request, or diff them
between releases:

* ``docs/studio-preview.html``  - the Studio control panel (API calls are inert
  without the server, and the page says so rather than failing silently).
* ``docs/dashboard-preview.html`` - a dashboard rendered from the newest run under
  ``artifacts/`` (or from ``--run``).

Usage::

    python scripts/render_ui_previews.py                 # newest run in artifacts/
    python scripts/render_ui_previews.py --run artifacts/final-demo
    python scripts/render_ui_previews.py --check         # fail if regeneration differs
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

STUDIO_PREVIEW = REPO_ROOT / "docs" / "studio-preview.html"
DASHBOARD_PREVIEW = REPO_ROOT / "docs" / "dashboard-preview.html"

STUDIO_HEADER = """<!--
  Static preview of the Studio shell, generated by scripts/render_ui_previews.py.
  The live server (`insilico-trial studio`) serves the same markup; without it the
  API calls fail harmlessly and the status line says so.
-->
"""


def render_studio_preview() -> Path:
    from insilico_trial_mas.ui import studio

    STUDIO_PREVIEW.write_text(STUDIO_HEADER + studio.STUDIO_HTML, encoding="utf-8")
    return STUDIO_PREVIEW


def render_dashboard_preview(run: str | None) -> Path | None:
    from insilico_trial_mas.ui.dashboard import build_dashboard
    from insilico_trial_mas.ui.data import load_dashboard_data, resolve_run_dir

    if run is None:
        candidates = sorted((REPO_ROOT / "artifacts").glob("*/RUN-*"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not candidates:
            print("no run found under artifacts/ - skipping the dashboard preview", file=sys.stderr)
            return None
        target = candidates[0]
    else:
        target = Path(run)
    run_dir = resolve_run_dir(target)
    DASHBOARD_PREVIEW.write_text(build_dashboard(load_dashboard_data(run_dir)), encoding="utf-8")
    print(f"dashboard preview rendered from {run_dir}")
    return DASHBOARD_PREVIEW


def main() -> int:
    parser = argparse.ArgumentParser(description="Render UI previews into docs/")
    parser.add_argument("--run", default=None, help="run directory or parent directory (defaults to the newest)")
    parser.add_argument("--check", action="store_true", help="do not write; fail if a preview is missing")
    args = parser.parse_args()

    if args.check:
        # Deliberately dependency-free: this runs on a bare CI runner to catch a
        # stale committed preview, which must not require the scientific stack.
        missing = [path for path in (STUDIO_PREVIEW, DASHBOARD_PREVIEW) if not path.exists()]
        for path in missing:
            print(f"missing UI preview: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        if missing:
            return 1
        for path in (STUDIO_PREVIEW, DASHBOARD_PREVIEW):
            print(f"UI preview present: {path.relative_to(REPO_ROOT)} ({path.stat().st_size // 1024} KB)")
        return 0

    studio_path = render_studio_preview()
    print(f"studio preview written to {studio_path.relative_to(REPO_ROOT)}")
    render_dashboard_preview(args.run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
